// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-d4n2on3ZHPWDCb1_5MCo10oaxSUkipk',
    appId: '1:664126669022:web:09b446840ca7100d28824f',
    messagingSenderId: '664126669022',
    projectId: 'testing-cli-a9257',
    authDomain: 'testing-cli-a9257.firebaseapp.com',
    storageBucket: 'testing-cli-a9257.appspot.com',
    measurementId: 'G-SJ1FCRN27B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEic4xtknTmhUpbipzB8MtH3k9O9h84aE',
    appId: '1:664126669022:android:9e3665d7d6cd2ec728824f',
    messagingSenderId: '664126669022',
    projectId: 'testing-cli-a9257',
    storageBucket: 'testing-cli-a9257.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDko_Il30iLoLVvfTEDt_mk7tRO9vg5EBs',
    appId: '1:664126669022:ios:0cb22df33cf4a58c28824f',
    messagingSenderId: '664126669022',
    projectId: 'testing-cli-a9257',
    storageBucket: 'testing-cli-a9257.appspot.com',
    iosBundleId: 'com.example.firebaseAsif',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDko_Il30iLoLVvfTEDt_mk7tRO9vg5EBs',
    appId: '1:664126669022:ios:0cb22df33cf4a58c28824f',
    messagingSenderId: '664126669022',
    projectId: 'testing-cli-a9257',
    storageBucket: 'testing-cli-a9257.appspot.com',
    iosBundleId: 'com.example.firebaseAsif',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-d4n2on3ZHPWDCb1_5MCo10oaxSUkipk',
    appId: '1:664126669022:web:a2376b679f6b7da328824f',
    messagingSenderId: '664126669022',
    projectId: 'testing-cli-a9257',
    authDomain: 'testing-cli-a9257.firebaseapp.com',
    storageBucket: 'testing-cli-a9257.appspot.com',
    measurementId: 'G-59G4LCXGZ3',
  );
}
